name: Test
description: Test
inputs:
  status:
    description: Status of job
    default: ${{ job.status }}
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
branding:
  icon: archive
  color: gray-dark

