name: Release

on:
  pull_request_target:
    types:
    - labeled
    - opened
    - synchronize

jobs:
  release:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    name: Release
    uses: TrueBrain/OpenTTD-actions/.github/workflows/rw-docker-build.yml@reusing-workflows
    with:
      publish: true

  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    needs:
    - release
    name: Deploy
    uses: TrueBrain/OpenTTD-actions/.github/workflows/rw-nomad-deploy.yml@reusing-workflows
    secrets: inherit
    with:
      is_preview: true
      service: wiki-preview
      url_production: https://wiki-preview.openttd.org/
      version: "@sha256:${{ needs.release.outputs.digest }}"

  preview_labels:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    needs:
    - deploy

    name: Update preview labels

    runs-on: ubuntu-latest

    steps:
    - name: Remove preview label from all other PRs
      run: |
        prs=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/search/issues?q=is:pr%20label:preview%20repo:OpenTTD/OpenTTD \
          | jq .items[].number)

        for pr in ${prs}; do
          if [ "${pr}" -eq "${{ github.event.pull_request.number }}" ]; then
            continue
          fi

          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${pr}/labels/preview"
        done

    # When two PRs get the Preview label before they can execute, the first will
    # remove the label from the second, and the second from the first. This would
    # leave no PR with a Preview label. So always make sure that if we finish,
    # our PR has a preview label.
    - name: Ensure we have a preview label
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
          -d '{"labels":["preview"]}'
